#!/bin/sh

start() {
 	echo -n "Starting respawnd: "
	start-stop-daemon --start --exec /sbin/respawnd
	echo "OK"
}
stop() {
	echo -n "Stopping respawnd: "
	start-stop-daemon --stop --oknodo --retry 5 --exec /sbin/respawnd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

