#!/bin/sh
#
# Starts httpd for the NetCOM web interface
#

start() {
 	echo -n "Starting httpd: "
	/usr/bin/update-http-passwords
	start-stop-daemon -S -q -b -m -p /var/run/httpd.pid --exec /usr/sbin/httpd -- -h /usr/share/html -c /etc/httpd.conf -f
	echo "OK"
}
stop() {
	echo -n "Stopping httpd: "
	start-stop-daemon -K -q -p /var/run/httpd.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

