#!/bin/sh

# This script reads the /etc/conf.d/http-passwords file and updates
# the /etc/httpd.conf configuration file.

HTTPD_CONF_TEMPLATE=/etc/httpd.conf.tmpl
HTTPD_CONF=/tmp/httpd.conf

cp ${HTTPD_CONF_TEMPLATE} ${HTTPD_CONF}

# Update the passwords
cat /etc/conf.d/http-passwords | while read l ; do
    user=$(echo $l | cut -f1 -d':')
    pass=$(echo $l | cut -f2 -d':')

    if [ -z "$pass" ]; then
	sed -i "s%^\(# \)\?\([^:]*\):$user:.*$%# \2:$user:%" ${HTTPD_CONF}
    else
	sed -i "s%^\(# \)\?\([^:]*\):$user:.*$%\2:$user:$pass%" ${HTTPD_CONF}
    fi
done
