#! /bin/sh

# Update the bootloaders as necessary

. /etc/init.d/functions.sh

begin "Checking bootloaders"

at91boot_ver=$(fw_printenv -n at91boot_ver) 2> /dev/null
new_at91boot_ver=$(cat /usr/share/netcom/dataflash_at91sam9m10g45ek.ver)

if [ "$at91boot_ver" != "$new_at91boot_ver" ]; then
  [ -e /usr/sbin/flashcp ] || \
    logger -t bootstrap -p err "Failed - Flashcp missing" &&\
    error "Failed"
  information "Updating at91bootstrap from version: $at91boot_ver to version: $new_at91boot_ver"
  warning "Do not turn off during update."
  flash_erase /dev/mtd/at91bootstrap 0 0 && \
  flashcp /usr/share/netcom/dataflash_at91sam9m10g45ek.bin /dev/mtd/at91bootstrap && \
  fw_setenv at91boot_ver $new_at91boot_ver && \
  information "Done" && reboot=1 || \
    logger -t bootstrap -p err "Failed to update at91bootstrap" && \
    error "Failed to update at91bootstrap"
fi


uboot_ver=$(fw_printenv -n uboot_ver) 2> /dev/null
new_uboot_ver=$(cat /usr/share/netcom/u-boot.ver)

if [ "$uboot_ver" != "$new_uboot_ver" ]; then
  echo timer > /sys/class/leds/pwr-lan/trigger
  echo 50 > /sys/class/leds/pwr-lan/delay_on
  echo 50 > /sys/class/leds/pwr-lan/delay_off
  echo timer > /sys/class/leds/error/trigger
  echo 50 > /sys/class/leds/error/delay_on
  echo 50 > /sys/class/leds/error/delay_off
  information "Updating u-boot from version: $uboot_ver to version: $new_uboot_ver"
  warning "Do not turn off during update."
  flash_erase /dev/mtd/u-boot 0 0 && \
  flashcp /usr/share/netcom/u-boot.bin /dev/mtd/u-boot && \
  fw_setenv uboot_ver $new_uboot_ver && \
  information "Done" && reboot=1 || \
    logger -t bootstrap -p err "Failed to update u-boot" && \
    error "Failed"
  echo network > /sys/class/leds/pwr-lan/trigger
  echo none > /sys/class/leds/error/trigger
fi

[ "$reboot" == "1" ] && reboot

end 0

exit 0
