#!/bin/sh
#
# Starts dropbear sshd.
#

DROPBEAR_CONFDIR=/etc/conf.d/dropbear

# Make sure the dropbearkey progam exists
[ -f /usr/bin/dropbearkey ] || exit 0

start() {
 	echo -n "Starting dropbear sshd: "
	# Make sure dropbear directory exists
	if [ ! -d ${DROPBEAR_CONFDIR} ] ; then
		mkdir -p ${DROPBEAR_CONFDIR}
	fi
	# Check for the Dropbear RSA key
	if [ ! -f ${DROPBEAR_CONFDIR}/dropbear_rsa_host_key ] ; then
		echo -n "generating rsa key... "
		/usr/bin/dropbearkey -t rsa -f ${DROPBEAR_CONFDIR}/dropbear_rsa_host_key > /dev/null 2>&1
	fi

	# Check for the Dropbear DSS key
	if [ ! -f ${DROPBEAR_CONFDIR}/dropbear_dss_host_key ] ; then
		echo -n "generating dsa key... "
		/usr/bin/dropbearkey -t dss -f ${DROPBEAR_CONFDIR}/dropbear_dss_host_key > /dev/null 2>&1
	fi
	umask 077
	start-stop-daemon -S -q -p /var/run/dropbear.pid \
	    --exec /usr/sbin/dropbear -- \
	    -d ${DROPBEAR_CONFDIR}/dropbear_dss_host_key \
	    -r ${DROPBEAR_CONFDIR}/dropbear_rsa_host_key
	echo "OK"
}
stop() {
	echo -n "Stopping dropbear sshd: "
	start-stop-daemon -K -q -p /var/run/dropbear.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

