#! /bin/sh

set -e

DESC="vsftpd"
NAME=vsftpd
DAEMON=/usr/sbin/$NAME

case "$1" in
  manual-start)
	echo -n "Starting $DESC: "
	start-stop-daemon -S -b -x $NAME
	echo "OK"
	;;
  manual-stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x $NAME
	echo "OK"
	;;
  manual-restart)
	echo "Restarting $DESC: "
	$0 stop
	sleep 1
	$0 start
	echo ""
	;;
  start)
	# Do nothing, this service should not be started automatically
	;;
  stop)
	# Do nothing, this service should not be started automatically
	;;
  restart)
	# Do nothing, this service should not be started automatically
	;;
  *)
	echo "Usage: $0 {start|stop|restart|manual-start|manual-stop|manual-restart}" >&2
	exit 1
	;;
esac

exit 0
