#!/bin/sh

# Extract the daemon name from the symbolic link used to call ourself,
# and remove the Sxx prefix.
DAEMON=$(basename $0 | sed 's/^S[0-9][0-9]//')

. /etc/init.d/functions.sh

if test -f /etc/conf.d/$DAEMON.service ; then
    . /etc/conf.d/$DAEMON.service
else
    enabled=0
fi

if test -f /usr/share/netcom/$DAEMON.startupdb ; then
    . /usr/share/netcom/$DAEMON.startupdb
fi

manual_start() {
	    begin "Starting $DAEMON"
            if ! eval "$license" 2>&1 > /dev/null ; then
                end 1 "No license"
                return
            fi

	    if test -f /etc/init.d/$DAEMON.prestart ; then
		/etc/init.d/$DAEMON.prestart
	    fi

	    start_daemon /usr/bin/$DAEMON "$options"
	    end $?
}

start() {
	if test $enabled -eq 1 ; then
	    manual_start
	fi
}

manual_stop() {
	    begin "Stopping $DAEMON"
	    stop_daemon /usr/bin/$DAEMON
	    end $?
}

stop() {
	if test $enabled -eq 1 ; then
	    manual_stop
	fi
}

restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  manual-start)
	manual_start
	;;
  manual-stop)
	manual_stop
	;;
  restart|reload)
        restart
        ;;
  *)
        echo $"Usage: $0 {start|stop|manual-start|manual-stop|restart}"
        exit 1
esac

exit $?
