#!/bin/sh

. /etc/init.d/functions.sh

start() {
	    begin "Starting netcomlocator"
	    start_daemon /usr/bin/netcomlocator
	    end $?
}

stop() {
	    begin "Stopping netcomlocator"
	    stop_daemon /usr/bin/netcomlocator
	    end $?
}

restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
